title: Satyam Sharma
#logo: ![imagess]({{ '/assets/imagess.jpg' | /blob/main/assets/imagess.jpg}}) # Use a relative path to logo image 
logo: /assets/img/imagess.jpg
#![Replica logo]({{ '/images/replica_logo_2.jpeg' | relative_url }})
# https://github.com/ssharma01x/portfolio/blob/main/assets/image12.png

description: Data Analytics, Risk Management, Finance # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

email: ssharmamacster@gmail.com # Allow visitors to contact you
