title: Satyam Sharma
logo: ![imagess](/assets/152207319/f0cecc84-7b45-4161-b7a0-dd932e077e52)portfolio/blob/main/assets/imagess.JPG # Use a relative path to logo image 

# https://github.com/ssharma01x/portfolio/blob/main/assets/image12.png

description: Data science and AI in risk and finance # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

email: ssharmamacster@gmail.com # Allow visitors to contact you
