title: Satyam Sharma
logo: /assets/img # Use a relative path to logo image 
# https://github.com/ssharma01x/portfolio/blob/main/assets/image12.png
# https://github.com/ssharma01x/portfolio/blob/main/assets/imagess.jpg
description: Data science and AI in risk and finance # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

email: ssharmamacster@gmail.com # Allow visitors to contact you
